### PR TITLE
Added Loader-22

### PR DESCRIPTION
**Pull request by AjayMaheshwari23**
I have added a new loader , kindly review it .

### CODE REVIEW

**Comment by AjayMaheshwari23** [comment]
can you please give hactoberfest labels for this PR . Thank You

**Comment by rohit8020** [comment]
Thanks for contributing @AjayMaheshwari23 
Star the [repo](https://github.com/rohit8020/css-loaders) and follow me on [github](https://github.com/rohit8020).

**Comment by rohit8020** [comment]
> can you please give hactoberfest labels for this PR . Thank You

Done. Thanks for reminding.

**Comment by rohit8020** [comment]
> can you please give hactoberfest labels for this PR . Thank You

Done. Thanks for Reminding.

**Pull request merged**
